version: '3'
services:
  chrome:
    build: .
    container_name: veriff-chrome
    command: npx cypress run
    volumes:
      - ./cypress:/cypress
      - ./package.json:/package.json
      - ./cypress.config.js:/cypress.config.js

  electron:
    build: .
    container_name: veriff-headless
    command: cypress run --headed
    volumes:
      - ./cypress:/cypress
      - ./package.json:/package.json
      - ./cypress.config.js:/cypress.config.js
